export const config = {
    SPREADSHEET_ID: '1NHlnoy81O69YUrukKFeC9_mPnJqUZT5cjGl4Jx67En8',
    RANGE: 'HenryProjects',
    MAJOR_DIMENSIONS: 'ROWS',
    VALUE_RENDER_OPTION: 'FORMATTED_VALUE',
    DATE_TIME_RENDER_OPTION: 'FORMATTED_STRING',
}